// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0SvtY4C9I5gwmZ2YahzF6fnV8dKfVodg',
    appId: '1:582495230915:web:4a90b6a6597d69a573bb76',
    messagingSenderId: '582495230915',
    projectId: 'majordomo-16c3d',
    authDomain: 'majordomo-16c3d.firebaseapp.com',
    databaseURL: 'https://majordomo-16c3d.firebaseio.com',
    storageBucket: 'majordomo-16c3d.appspot.com',
    measurementId: 'G-BTW4D1CPSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgokOKt5FAmjC2vo7_iUW9zAOnGj7QZ1w',
    appId: '1:582495230915:android:29e6f39c02c0d74e73bb76',
    messagingSenderId: '582495230915',
    projectId: 'majordomo-16c3d',
    databaseURL: 'https://majordomo-16c3d.firebaseio.com',
    storageBucket: 'majordomo-16c3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD480g6FubuQod6Aw70JpTwpON49DrEKi0',
    appId: '1:582495230915:ios:25285e3dc859d6c373bb76',
    messagingSenderId: '582495230915',
    projectId: 'majordomo-16c3d',
    databaseURL: 'https://majordomo-16c3d.firebaseio.com',
    storageBucket: 'majordomo-16c3d.appspot.com',
    iosBundleId: 'com.majordomo.homeApp',
  );
}
